-- 创建租户表
CREATE TABLE Tenants (
    TenantID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedBy TEXT,
    IsDeleted BOOLEAN DEFAULT 0
);

-- 创建用户表
CREATE TABLE Users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantID INTEGER,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedBy TEXT,
    IsDeleted BOOLEAN DEFAULT 0,
    FOREIGN KEY(TenantID) REFERENCES Tenants(TenantID)
);

-- 创建表单表
CREATE TABLE Forms (
    FormID INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantID INTEGER,
    Name TEXT NOT NULL,
    Description TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedBy TEXT,
    IsDeleted BOOLEAN DEFAULT 0,
    FOREIGN KEY(TenantID) REFERENCES Tenants(TenantID)
);

-- 创建字段表
CREATE TABLE Fields (
    FieldID INTEGER PRIMARY KEY AUTOINCREMENT,
    FormID INTEGER,
    Name TEXT NOT NULL,
    Type TEXT NOT NULL,
    Constraints TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedBy TEXT,
    IsDeleted BOOLEAN DEFAULT 0,
    FOREIGN KEY(FormID) REFERENCES Forms(FormID)
);

-- 创建表单数据表
CREATE TABLE FormData (
    EntryID INTEGER PRIMARY KEY AUTOINCREMENT,
    FormID INTEGER,
    Data TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    SubmittedBy TEXT,
    IsDeleted BOOLEAN DEFAULT 0,
    FOREIGN KEY(FormID) REFERENCES Forms(FormID)
);

-- 创建套餐表
CREATE TABLE Plans (
    PlanID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    MaxUsers INTEGER,
    MaxForms INTEGER,
    MaxEntries INTEGER,
    Price DECIMAL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 创建租户套餐关联表
CREATE TABLE TenantPlans (
    TenantPlanID INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantID INTEGER,
    PlanID INTEGER,
    StartDate DATETIME,
    EndDate DATETIME,
    IsActive BOOLEAN DEFAULT 1,
    FOREIGN KEY(TenantID) REFERENCES Tenants(TenantID),
    FOREIGN KEY(PlanID) REFERENCES Plans(PlanID)
);

-- 创建账单表
CREATE TABLE Billings (
    BillingID INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantID INTEGER,
    Amount DECIMAL,
    BillingDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    DueDate DATETIME,
    Status TEXT,
    FOREIGN KEY(TenantID) REFERENCES Tenants(TenantID)
);

-- 创建使用量跟踪表
CREATE TABLE UsageTracking (
    UsageID INTEGER PRIMARY KEY AUTOINCREMENT,
    TenantID INTEGER,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    UserCount INTEGER,
    FormCount INTEGER,
    EntryCount INTEGER,
    FOREIGN KEY(TenantID) REFERENCES Tenants(TenantID)
);

ALTER TABLE Users
ADD COLUMN email VARCHAR(255);